name: Deploy

# Deploys on pushes to main, as well as every hour.
on:
  push:
    branches:
      - main
  # schedule:
  #   - cron: "0 * * * *"
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Sync calendar
        run: "${GITHUB_WORKSPACE}/sync.sh"
      - uses: enriikke/gatsby-gh-pages-action@v2
        with:
          access-token: ${{ secrets.ACCESS_TOKEN }}
          deploy-branch: gh-pages
